# Site settings
title: まつまつの部屋
email: songsongdahu233@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: ""
url: "https://matsumatsu233.github.io" # the base hostname & protocol for your site
pagination:
  permalink: '/page/:num/'
  enabled: true
  per_page: 10
  sort_field: 'date'
  sort_reverse: true

author:
  name: まつまつ
  twitter: ssdh233
  github: matsumatsu233
  email: songsongdahu233@gmail.com
  youtube: UCUSkvp3mmI31TClMIflzT0g

disqus:
  id: matsumatsu

projects:
  - title: Gitadora-Skill-Viewer
    url: "http://gsv.fun"
    description: ギタドラのスキルデータを保存するウェブサイトgsv.fun。
  - title: Mahjong-Tiles-Converter
    url: "/mtc/"
    description: 麻雀牌を表示するhtmlを自動的に生成する便利なツールです。


# Build settings
markdown: kramdown

gems: [jekyll-paginate-v2]
plugins_dir:
  - jekyll-paginate-v2