# Site settings
title: まつまつの部屋
email: songsongdahu233@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: ""
url: "https://matsumatsu233.github.io" # the base hostname & protocol for your site

author:
  name: まつまつ
  twitter: ssdh233
  github: matsumatsu233
  email: songsongdahu233@gmail.com
  youtube: UCUSkvp3mmI31TClMIflzT0g

disqus:
  id: matsumatsu

projects:
  - title: Gitadora-Skill-Viewer
    suburl: "gsv"
    description: ギタドラのスキルデータを保存するウェブサイトgsv.fun。
  - title: Mahjong-Tiles-Converter
    suburl: "mtc/"
    description: 麻雀牌を表示するhtmlを自動的に生成する便利なツールです。


# Build settings
markdown: kramdown
